"""Add OuiEntry table

Revision ID: 2c9c9eb928c3
Revises: 84d6a692d6a4
Create Date: 2026-07-01 03:11:21.011428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9c9eb928c3'
down_revision: Union[str, Sequence[str], None] = '84d6a692d6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oui_entries',
    sa.Column('mac_prefix', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mac_prefix')
    )
    op.create_index(op.f('ix_oui_entries_mac_prefix'), 'oui_entries', ['mac_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oui_entries_mac_prefix'), table_name='oui_entries')
    op.drop_table('oui_entries')
    # ### end Alembic commands ###
